In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2],[3,4]])

In [4]:
arr1

array([[1, 2],
       [3, 4]])

In [7]:
h_vector = np.array([1,2,3,4])
v_vector = np.array([4,3,2,1])
product = np.dot(h_vector,v_vector)
product

20

In [8]:
h_vector.shape

(4,)

In [9]:
h_matrix = np.array([[1,2,3,4]])

In [10]:
v_matrix = np.array([[1],[2],[3],[4]])

In [11]:
matrix_product = h_matrix@v_matrix

In [12]:
matrix_product

array([[30]])

In [13]:
h_matrix.shape

(1, 4)

In [14]:
arr_0 = np.zeros([4,5])

In [15]:
arr_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
step_array = np.arange(0,100,2)
step_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [18]:
rnd = np.random.permutation(50)
rnd

array([ 2, 46, 39,  6,  3, 25,  7, 15,  8, 38, 24, 31, 14, 21, 35, 30, 43,
       40, 11, 19, 29, 20, 49, 37, 42, 26, 23, 44, 18, 36, 45, 32, 28, 27,
        9, 10, 48,  5, 17, 12, 41, 34,  0, 13, 22, 33, 16,  1, 47,  4])